version: "1"

services:
  - type: web
    name: lux-n8n
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: frankfurt
    envVars:
      - key: NODE_ENV
        value: production
      - key: N8N_RUNNERS_ENABLED
        value: true
      - key: N8N_EXECUTIONS_MODE
        value: "queue"
      - key: N8N_HOST
        sync: false
      - key: N8N_EDITOR_BASE_URL
        sync: false
    healthCheckPath: /healthz
    autoDeploy: true
