version: "1"

services:
  - type: web
    name: n8n-v2
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: N8N_USER_FOLDER
        value: /opt/render/.n8n
      - key: N8N_HOST
        value: ${RENDER_SERVICE_NAME}.onrender.com
      - key: N8N_EDITOR_BASE_URL
        value: https://${RENDER_SERVICE_NAME}.onrender.com
    disk:
      name: disk
      mountPath: /opt/render/.n8n
      sizeGB: 1
    healthCheckPath: /healthz
    autoDeploy: false
